#!/bin/bash

LONG_DATE=`date +%Y%m%d%H%M%S`

TOMCAT=tomcat6
TOMCAT_USER=tomcat6
TOMCAT_HOME=/var/lib/tomcat6
APACHE_CONF=/etc/apache2
SOURCE_DIR=/usr/share/dataone-cn-rest
SCRIPT_DIR=${SOURCE_DIR}/debian
JK_CONF=cn_jk.conf
###############################################################################
# Install CN war file
###############################################################################

## Stop tomcat
echo "Stopping Tomcat"
/etc/init.d/${TOMCAT} stop

## backup the old war file
if [ -e ${TOMCAT_HOME}/webapps/cn.war ]
then
  echo "Backing up ${TOMCAT_HOME}/webapps/cn.war to ${TOMCAT_HOME}/webapps/cn.war.${LONG_DATE}"
  mv ${TOMCAT_HOME}/webapps/cn.war ${TOMCAT_HOME}/webapps/cn.war.${LONG_DATE}
fi  

## remove the cn application directory
if [ -d ${TOMCAT_HOME}/webapps/cn ]
then
  echo "Removing the old CN application directories"
  rm -rf ${TOMCAT_HOME}/webapps/cn
fi 

## copy the new war file into the webapps directory
echo copying new cn.war file to ${TOMCAT_HOME}/webapps/cn.war
cp ${SOURCE_DIR}/cn.war ${TOMCAT_HOME}/webapps/cn.war
chown -R ${TOMCAT_USER}.${TOMCAT_USER} ${TOMCAT_HOME}/webapps/cn.war

## expand the war file
CURR_DIR=`pwd`

## make cn directory and extract cn.war into it.
echo "Making cn application directory: ${TOMCAT_HOME}/webapps/cn"
mkdir ${TOMCAT_HOME}/webapps/cn
cd ${TOMCAT_HOME}/webapps/cn

echo "extracting cn.war into ${TOMCAT_HOME}/webapps/cn"
jar -xvf ${TOMCAT_HOME}/webapps/cn.war > /dev/null
chown -R ${TOMCAT_USER}.${TOMCAT_USER} ${TOMCAT_HOME}/webapps/cn
echo cd to $CURR_DIR
cd $CURR_DIR


###############################################################################
# Configure Tomcat
###############################################################################

# Configure the context file
cp ${SCRIPT_DIR}/cn.xml ${TOMCAT_HOME}/conf/Catalina/localhost/
chown -R ${TOMCAT_USER}.${TOMCAT_USER} ${TOMCAT_HOME}/conf/Catalina/localhost/cn.xml
# Add permissions needed by cn
cp ${SCRIPT_DIR}/54cn.policy ${TOMCAT_HOME}/conf/policy.d/
chown -R ${TOMCAT_USER}.${TOMCAT_USER} ${TOMCAT_HOME}/conf/policy.d/54cn.policy

# this is a bit awkward and will need to be REMOVED!!!!! once nodeList is maintained
# somewhere sensible 
ln -t ${TOMCAT_HOME}/webapps/cn /var/lib/dataone/nodeList.xml 

###############################################################################
# Configure Apache
###############################################################################

## Stop apache
echo "Stopping Apache"
/etc/init.d/apache2 stop

## copy in jk mount configuration file

if [ -e ${APACHE_CONF}/jk_mount/${JK_CONF} ]
then 
  JK_DIFF=`diff ${SCRIPT_DIR}/${JK_CONF} ${APACHE_CONF}/jk_mount/${JK_CONF}`
  if [ "${JK_DIFF}" != "" ]
  then
    echo "Backing up ${APACHE_CONF}/jk_mount/${JK_CONF} to ${APACHE_CONF}/jk_mount/${JK_CONF}.${LONG_DATE}"
    mv ${APACHE_CONF}/jk_mount/${JK_CONF} ${APACHE_CONF}/jk_mount/${JK_CONF}.${LONG_DATE}
  fi
fi
echo "Copying ${JK_CONF} site file to ${APACHE_CONF}/jk_mount/"
cp ${SCRIPT_DIR}/${JK_CONF} ${APACHE_CONF}/jk_mount/



###############################################################################
# Start Apache and Tomcat
###############################################################################

## Start Apache
/etc/init.d/apache2 start


## Start Tomcat
echo "starting Tomcat server"


/etc/init.d/${TOMCAT} start


